# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: github-actions-azure-devops-key-vault

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    
- task: FileTransform@1
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/**/*.zip'
    fileType: 'json'
    targetFiles: '**/appsettings.json'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Avanade Azure Subscription'
    appType: 'webAppLinux'
    WebAppName: 'github-actions-azure-devops-integration-examples'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'DOTNETCORE|3.1'