name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore source/Library/Library.csproj
    - name: Build
      run: dotnet build source/Library/Library.csproj --configuration Release --no-restore
    - name: Generate Nuget package
      run: dotnet pack source/Library/Library.csproj --configuration Release
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: source/Library/bin/Release/Library.1.0.0.nupkg
    - name: Publish package
      run: dotnet nuget push source/Library/bin/Release/Library.1.0.0.nupkg --source "github"
