name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.5.0
      with:
        source-url: https://nuget.pkg.github.com/<owner>/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Install dependencies
      run: dotnet restore source/Library/Library.csproj

    - name: Build
      run: dotnet build source/Library/Library.csproj --configuration Release --no-restore

    - name: Generate Nuget package
      run: dotnet pack source/Library/Library.csproj --configuration Release

    - uses: actions/upload-artifact@v2
      with:
        path: source/Library/bin/Release/Library.1.0.0.nupkg

    - name: NuGet push
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github --username ${{ github.repository_owner }} --password ${{ github.token }} --store-password-in-clear-text
        dotnet nuget push **/*.nupkg --source github --api-key ${{ secrets.PACKAGE_TOKEN }}